---
apiVersion: v1
kind: Secret
metadata:
  name: envoy-ai-gateway-basic-aws-credentials
  namespace: default
type: Opaque
stringData:
  # Replace this with your AWS credentials.
  # You can also use AWS IAM roles for service accounts (IRSA) in EKS.
  credentials: |
    [default]
    aws_access_key_id = <aws_access_key_id>
    aws_secret_access_key = <aws_secret_access_key>